version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
    - MYSQL_DATABASE=nodedb
    - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodeapp-network
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/

  node-app:
    build:
      context: node
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh 
    command: ["node", "index.js"]
    tty: true
    networks:
      - nodeapp-network
    depends_on:
      - db
  
  nginx:
    build:
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://node-app:3000 -timeout 20s /docker-entrypoint.sh
    command: [ "nginx", "-g", "daemon off;" ]
    networks:
      - nodeapp-network
    depends_on:
      - node-app
    ports:
      - "8080:80"

networks:
  nodeapp-network:
    driver: bridge